<a href="https://colab.research.google.com/github/manelacavalcant/calculo-numerico/blob/main/EP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [ ]:
# item b): Eliminação de Gauss

def Gauss(A):  # tem como parâmetro a matriz aumentada

  n = A.shape[0]  # número de linhas da matriz
  for i in range(n):
    pivo = np.abs(A[i:, i])  # pivô; checando a submatriz de acordo com i
    m = np.argmax(pivo) + i  # índice do pivô

    if m != i:
      A[[i, m]] = A[[m, i]]  # troca de linhas
      print('Troca de linhas: ',i, ' com ', m)
      print(A)

    for j in range(i + 1, n):  # escalonando
      fator = A[j, i] / A[i, i]
      A[j, i:] -= fator * A[i, i:]  # zerando os itens abaixo do pivô
      print(A)

  X = np.zeros((n,1))  # vetor solução
  for i in range(n - 1, -1, -1):  # substituição para trás
    X[i,0] = ( A[i,-1]-np.sum(A[i,i:-1]*X[i:,0]) )/A[i,i]
  print('Matriz solução:\n',X)

  return X

def mainGauss():

  M = np.array([ [0.0,5.3,-1.8,3.1],[11.9,0.0,1.8,15.0],[1.0,-1.0,-1.0,0.0]])
  print(M)
  m = Gauss(M)
  teste = np.matmul(M[:,:-1],m)  # multiplicação dos coeficientes pela matriz solução
  print('Teste:\n',teste)

mainGauss()

[[ 0.   5.3 -1.8  3.1]
 [11.9  0.   1.8 15. ]
 [ 1.  -1.  -1.   0. ]]
Troca de linhas:  0  com  1
[[11.9  0.   1.8 15. ]
 [ 0.   5.3 -1.8  3.1]
 [ 1.  -1.  -1.   0. ]]
[[11.9  0.   1.8 15. ]
 [ 0.   5.3 -1.8  3.1]
 [ 1.  -1.  -1.   0. ]]
[[11.9        0.         1.8       15.       ]
 [ 0.         5.3       -1.8        3.1      ]
 [ 0.        -1.        -1.1512605 -1.2605042]]
[[11.9         0.          1.8        15.        ]
 [ 0.          5.3        -1.8         3.1       ]
 [ 0.          0.         -1.49088315 -0.67559854]]
Matriz solução:
 [[1.19196001]
 [0.73880676]
 [0.45315325]]
Teste:
 [[15.        ]
 [ 3.1       ]
 [-0.67559854]]


In [ ]:
# item c): Método de Jacobi

def Jacobi(A,b):  # tem como parâmetro as matrizes de coeficientes e de resultados

  epsilon = 10**(-3)  # critério de parada
  n = A.shape[0]  # número de linhas da matriz
  Xk = np.zeros((n,1))  # vetor solução
  Xk1 = np.ones((n,1))  # vetor auxiliar
  k = 0  # contador de iterações

  while np.linalg.norm(Xk1-Xk, ord=np.inf) >= epsilon:
    Xk = np.copy(Xk1)
    k += 1
    print('k = ',k)

    for j in range(n):  # laço para as linhas
      esq = np.sum(A[j,:j]*Xk[:j,0])  # à esquerda de A[j,j]
      dir = np.sum(A[j,j+1:]*Xk[j+1:,0])  # à direita de A[j,j]
      Xk1[j,0] = (b[j,0] - dir - esq)/A[j,j]
    print('X = ',Xk1,'\n','erro = ',np.linalg.norm(Xk1-Xk, ord=np.inf),'\n')

  return Xk1

def mainJacobi():
  # duas primeiras linhas permutadas:
  M = np.array([ [11.9,0.0,1.8],[0.0,5.3,-1.8],[1.0,-1.0,-1.0] ])
  b = np.array([ [15.0],[3.1],[0.0] ])
  print('A = ',M,'\n')
  print('b = ',b,'\n')
  j = Jacobi(M,b)

mainJacobi()


A =  [[11.9  0.   1.8]
 [ 0.   5.3 -1.8]
 [ 1.  -1.  -1. ]]
b =  [[15. ]
 [ 3.1]
 [ 0. ]]
k =  1
X =  [[ 1.1092437]
 [ 0.9245283]
 [-0.       ]] 
 erro =  1.0 

k =  2
X =  [[1.2605042 ]
 [0.58490566]
 [0.1847154 ]] 
 erro =  0.3396226415094341 

k =  3
X =  [[1.23256406]
 [0.64763919]
 [0.67559854]] 
 erro =  0.4908831457111149 

k =  4
X =  [[1.15831283]
 [0.81435422]
 [0.58492487]] 
 erro =  0.16671503061886916 

k =  5
X =  [[1.17202817]
 [0.78355939]
 [0.3439586 ]] 
 erro =  0.2409662627432394 

k =  6
X =  [[1.20847685]
 [0.70172179]
 [0.38846878]] 
 erro =  0.08183759866751528 

k =  7
X =  [[1.20174422]
 [0.71683845]
 [0.50675506]] 
 erro =  0.11828627706565231 

k =  8
X =  [[1.18385218]
 [0.75701115]
 [0.48490576]] 
 erro =  0.04017269787135358 

k =  9
X =  [[1.18715711]
 [0.74959064]
 [0.42684102]] 
 erro =  0.0580647397804438 

k =  10
X =  [[1.19594001]
 [0.72987054]
 [0.43756647]] 
 erro =  0.019720100302792254 

k =  11
X =  [[1.19431768]
 [0.73351314]
 [0.46606948]] 
 

In [ ]:
# item d):

A = np.array([ [11.9,0.0,1.8],[0.0,5.3,-1.8],[1.0,-1.0,-1.0] ])
J = np.zeros((3,3))
for i in range(3):  # linhas
  J[i,i+1:] = A[i,i+1:]/A[i,i]
  J[i,:i] = A[i,:i]/A[i,i]
print(J)

lamda = 0.700631j
rho = np.abs(lamda)
k = math.log(10**(-3),rho)
print('k = ',k)

[[ 0.          0.          0.1512605 ]
 [ 0.          0.         -0.33962264]
 [-1.          1.          0.        ]]
k =  19.41613722446131


In [ ]:
# item e): Método de Gauss-Seidel

def GaussSeidel(A,b):  # tem como parâmetro as matrizes de coeficientes e de resultados

  epsilon = 10**(-3)  # critério de parada
  n = A.shape[0]  # número de linhas da matriz
  Xk = np.zeros((n,1))  # vetor solução
  Xk1 = np.ones((n,1))  # vetor atualizado
  k = 0  # contador de iterações

  while np.linalg.norm(Xk1-Xk, ord=np.inf) >= epsilon:
    Xk = np.copy(Xk1)
    k += 1
    print('k = ',k)

    for j in range(n):  # laço para as linhas
      esq = np.sum(A[j,:j]*Xk1[:j,0])  # à esquerda de A[j,j], usando o vetor atualizado
      dir = np.sum(A[j,j+1:]*Xk[j+1:,0])  # à direita de A[j,j]
      Xk1[j,0] = (b[j,0] - dir - esq)/A[j,j]
    print('X = ',Xk1,'\n','erro = ',np.linalg.norm(Xk1-Xk, ord=np.inf),'\n')

  return Xk1

def mainGS():
  # duas primeiras linhas permutadas:
  M = np.array([ [11.9,0.0,1.8],[0.0,5.3,-1.8],[1.0,-1.0,-1.0] ])
  b = np.array([ [15.0],[3.1],[0.0] ])
  print('A = ',M,'\n')
  print('b = ',b,'\n')
  g = GaussSeidel(M,b)

mainGS()


A =  [[11.9  0.   1.8]
 [ 0.   5.3 -1.8]
 [ 1.  -1.  -1. ]]
b =  [[15. ]
 [ 3.1]
 [ 0. ]] 

k =  1
X =  [[1.1092437]
 [0.9245283]
 [0.1847154]] 
 erro =  0.8152846044078012 

k =  2
X =  [[1.23256406]
 [0.64763919]
 [0.58492487]] 
 erro =  0.40020947126154327 

k =  3
X =  [[1.17202817]
 [0.78355939]
 [0.38846878]] 
 erro =  0.19645608419624827 

k =  4
X =  [[1.20174422]
 [0.71683845]
 [0.48490576]] 
 erro =  0.09643698060434192 

k =  5
X =  [[1.18715711]
 [0.74959064]
 [0.43756647]] 
 erro =  0.047339288401941015 

k =  6
X =  [[1.19431768]
 [0.73351314]
 [0.46080453]] 
 erro =  0.023238058806470452 

k =  7
X =  [[1.19080268]
 [0.74140531]
 [0.44939736]] 
 erro =  0.011407171407140093 

k =  8
X =  [[1.19252813]
 [0.73753118]
 [0.45499695]] 
 erro =  0.005599588184002857 

k =  9
X =  [[1.19168113]
 [0.73943293]
 [0.45224821]] 
 erro =  0.0027487434624502427 

k =  10
X =  [[1.19209691]
 [0.73849939]
 [0.45359752]] 
 erro =  0.0013493118376005642 

k =  11
X =  [[1.19189281]
 [0.73